"""Add is_blocked to User

Revision ID: 52707f89961d
Revises: 9123a0b5e537
Create Date: 2025-06-19 12:03:50.403031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52707f89961d'
down_revision = '9123a0b5e537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'is_blocked')
    # ### end Alembic commands ###
